apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberpro-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuberpro
  template:
    metadata:
      labels:
        app: kuberpro
    spec:
      containers:
        - name: kuberpro
          image: manalithamke/kuberpro
          ports:
            - containerPort: 80
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Served by $(hostname)" >> /usr/local/apache2/htdocs/index.html && \
              httpd-foreground